[default]
bot_name = "PROJECT NAME"
machine_name = "DEVICE NAME "
bot_user_name = "COMPUTER USER ACOUNT NAME"
business_unit = "BUSINESS NAME"
human_time = "ADD INT FOR HUMAN TIME TO PROCESS TASK MANUALLY"

[default.notifications]
from_email = "EMAIL SENDER"
to_email = "EMAIL RECEIVER"

[default.file_path]
input_file = "ADD INPUT FILE PATH"
output_file = "ADD OUTPUT FILE PATH"

# Add application types here
[default.applications]
browser = "ADD BROWSER NAME"

[default.applicaiton.path]
application_path_1 = "ADD LOCATION PATH FOR APPLICATION"

[default.sqlite_db]
table_name = "TABLE NAME"
metrics_table_name = "YOUR METRIC TABLE NAME"
db_file_path = "ADD EXTERNAL PATH HERE"

# Default Logging
[default.logging]
version = 1
disable_existing_loggers = false

[default.logging.formatters.simple]
format = "%(levelname)s: %(message)s"

[default.logging.formatters.detailed]
format = "[%(levelname)s|%(module)s|L%(lineno)d] %(asctime)s: %(message)s"
datefmt = "%Y-%m-%dT%H:%M:%S%z"

[default.logging.handlers.stderr]
class = "logging.StreamHandler"
level = "WARNING"
formatter = "simple"
stream = "ext://sys.stderr"

[default.logging.handlers.file]
class = "logging.handlers.RotatingFileHandler"
level = "INFO"
formatter = "detailed"
filename = "app.log"
maxBytes = 100_000_000
backupCount = 3

[default.logging.handlers.queue]
class = "logging.handlers.QueueHandler"
handlers = ["stderr", "file"]
respect_handler_level = "True"

[default.logging.loggers.root]
level = "DEBUG"
handlers = ["queue"]